### ISSUE TITLE
translation locally?

### ISSUE THREAD

**Issue by xeiki** [sayonari/twitchTransFree#3]
can you put a feature that the bot translates only locally?
i have some streamers they are japanese but i dont want to annoy the streamer or the other users on the channel.
is this makeable?
thanks.

**Comment by sayonari** [comment]
Thanks for your suggestion!
Do you mean "Do not post trans text to the chat!", right?

OK, I will implement it to my program.
Please wait....,

**Comment by sayonari** [comment]
Now, I implemented 'locally translation' option!!!
Please check the newest version.
