### ISSUE TITLE
Option to only translate one way?

### ISSUE THREAD

**Issue by upsetorandajin** [sayonari/twitchTransFree#4]
For example: Translating only English into Japanese for those who don't understand English in a Japanese stream.

It also seems to translate Japanese into Japanese and English into English sometimes. I have Default_Language set to ja and DefaultTransLanguage set to en but only want English to Japanese really.

(英語だけ翻訳したいですができないっぽいですね、英語だけ日本語に翻訳したい、日本語の場合は反応しない設定とか、しないと普通の日本語コメントで棒読みちゃん荒らしますね）

**Comment by sayonari** [comment]
All languages -> Japanese
Japanese -> (quiet)

It is possible to set these configs to 'ja'
```
Default_Language        = ja
Default_TransLanguage   = ja
```

comment:
If google translation fails to detect the language, the input text may be translated.
For example, if you enter Japanese, however, the system understand "the text is Chinese", the 
system will try to translate it into Japanese.

**Comment by upsetorandajin** [comment]
Thank you for your response! That indeed seems to be the problem I'm experiencing. When the translate fails to recognize the language even if it's just plain Japanese, it'll repeat itself which becomes quite annoying while running Bouyomichan.

Can't be helped I suppose!
